### ISSUE TITLE
Set Default Username and Password

### ISSUE THREAD

**Issue by vishnudas-raveendran** [vishnudas-raveendran/WCMS-Template1#1]
The user name and password can be set via the SQL dump provided.
Defaults to use:  username: admin, password: P@ssw0rd
Steps:
1. Use MD5 to hash the word "P@ssw0rd".
2. Write an insert query after the SQL command to create table Users in the ce.sql_Schema. The insert query should have 'admin' as user role and MD5 hash obtained earlier as password.
3. Commit the file.

Also, Mention the default username and password in the README file.

**Comment by adel-a** [comment]
I will work on this

**Comment by vishnudas-raveendran** [comment]
Sure, go ahead !!
Let me know if you face any issue in setup.

**Comment by vishnudas-raveendran** [comment]
> I will work on this

@adel-a Sure, Go ahead !! Let me know if you face any issue in setup.

**Comment by adel-a** [comment]
Thanks, will get back to you soon.

**Comment by vishnudas-raveendran** [comment]
Hi
@adel-a , Any updates? Do you need help ?

**Comment by luckymurari** [comment]
Hi @vishnudas-raveendran ,

I have created merge requests that fixes this. Please review and approve
