### ISSUE TITLE
Add docker-compose setup to the project

### ISSUE THREAD

**Issue by sebinbenjamin** [vishnudas-raveendran/WCMS-Template1#3]
Add docker to make the application easier to run with minimal config and requirements.

**Comment by vishnudas-raveendran** [comment]
That would be an interesting addition, wanted to work in docker. Thanks @sebinbenjamin  :)

**Comment by vishnudas-raveendran** [comment]
@sebinbenjamin Will make this a separate milestone?

**Comment by sebinbenjamin** [comment]
sure !

**Comment by vishnudas-raveendran** [comment]
#7 Pull request merged.

Closing the issue.
