### ISSUE TITLE
Images are not getting uploaded via Admin page

### ISSUE THREAD

**Issue by vishnudas-raveendran** [vishnudas-raveendran/WCMS-Template1#8]
"Error in uploading" message is shown when trying to add new entry in sections having an image upload in form.
The entry is reflected in the database but image is not getting uploaded to server.

**Comment by vishnudas-raveendran** [comment]
The error was due to insufficient privileges for write permissions (required for uploading) in server.

Will add instruction to give permission using chown for the web server.

Following instructions in https://stackoverflow.com/a/55084883/5107305

Find Web Server user

`ps aux | grep httpd`

In this case, its daemon Replace it with yours in next command.

`sudo chown -R daemon /opt/lampp/htdocs/[Working Project]/`

**Comment by vishnudas-raveendran** [comment]
Updated Readme file's installation section to prevent this issue.

**Comment by vishnudas-raveendran** [comment]
@sebinbenjamin  Would you have this issue for your docker setup? Could you please check?

**Comment by sebinbenjamin** [comment]
Yes, we have the issue for the docker setup too. Will work on it.
 
```
SESSION:Array ( [loggedin] => 1 )
POST:Array ( [title] => test [caption] => test [link] => test [submit] => insert )
FILES:Array ( [image] => Array ( [name] => IMG_20180925_171824.jpg [type] => image/jpeg [tmp_name] => /tmp/phpFHN8cR [error] => 0 [size] => 494099 ) )
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/admin/include/edit_news.php:3) in /var/www/html/admin/include/edit_news.php on line 62

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/admin/include/edit_news.php:3) in /var/www/html/admin/include/edit_news.php on line 67
```

**Comment by sreekar** [comment]
hlo how to upload  files in lampp using php
